### ISSUE TITLE
Writing Lab: Create guide for people submitting issues 

### ISSUE THREAD

**Issue by kategarklavs** [18F/g-content#7]
## Guide for people submitting issues

Topics to address include: 
- What we do, what we don’t do
- When you need to ask for a content designer
- Form for metadata
- Approval app
- Help with time estimates
- Guide to labels they should apply
- Difference between editing and approval
- Guide to milestones

**Comment by awfrancisco** [comment]
Guide for helpful titles.
Helpful ways to remind us that they have an open issue they want help on. 
Other content resources they can turn to. 
Way for them to give us feedback on the process.

**Comment by awfrancisco** [comment]
Starting a draft here. Please feel free to hop in and fill out these bullet points. https://docs.google.com/document/d/1R0xpaX4nTS1YARZ5GaCAuF1ZIqpO8JbLgZQk6MvssvE/edit

**Comment by awfrancisco** [comment]
Feeling pretty good about that draft. Would love feedback on the whole draft, but especially the questions I left in there. I'll post it in the channel next week as well and bring it up at the guild meeting.

**Comment by awfrancisco** [comment]
Guide posted https://pages.18f.gov/writing-lab-guide/
