### ISSUE TITLE
Writing Lab: Guide for Lab Contributors

### ISSUE THREAD

**Issue by kategarklavs** [18F/g-content#8]
This was an idea that came up during our 12/21 discussion of Writing Lab duties (as they relate to the work of the content tiger team).

Right now, Lab members use the 18F Content Guide and the AP Stylebook as their guides, but don't have any additional guidance. 

Some topics to consider including:
- Summary of Lab workflow (including how to close issues)
- Tips for offering feedback/interacting with Lab clients
- Troubleshooting difficult situations
- The Lab in relation to other content groups (g-content, tiger teams, XD content, etc.) — breakdown of duties

(Please add topics as you think of them!)

**Comment by awfrancisco** [comment]
Expectations for writing lab members.
Links to other specific resources like the Performance Profile Guide. 
Suggestions for ways to help improve Writing Lab work in the future including writing mini content guides, providing constructive feedback, ideas to help this scale. 
How to bill your writing lab time
How to ask for help on big projects (either from other lab members or from Russ)
Expanded background info on the stakeholder app. 
Tips on tone for edits - some people can be sensitive about critiques of their work. How to effectively communicate your edits.

**Comment by awfrancisco** [comment]
I also vote that these two guides live in the g-content repo and not writing-lab so that their ownership by g-content is clear and so that PRs/issues etc for the guides are kept out of the stream of writing-lab issues.

**Comment by kategarklavs** [comment]
@awfrancisco Yep, I'd filed the issues here (rather than in the Writing Lab repo) because I didn't want them to be confused for Lab issues!

**Comment by awfrancisco** [comment]
Guide posted https://pages.18f.gov/writing-lab-guide/
